"""Added timestamps to orgs

Revision ID: 93e5a1d11c0a
Revises: d2f183bfeb6f
Create Date: 2020-04-06 12:30:10.777939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "93e5a1d11c0a"
down_revision = "d2f183bfeb6f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column(
        "organizations",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "updated_at")
    op.drop_column("organizations", "created_at")
    # ### end Alembic commands ###
